/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5gscwvbztzh2tnhh5mvpkeltfe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-a5hiawt2ajewxppktqz7z5ljou",
    "aws_cognito_identity_pool_id": "us-east-1:ab6b6e8f-f47e-4471-b4eb-4ce2324a4377",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EbD7hWBnN",
    "aws_user_pools_web_client_id": "i1hung6pda8hjtj7f6se8o2uk",
    "oauth": {}
};


export default awsmobile;
